version: '3'
services: 
  web: 
    build: .
    stdin_open: true
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app  
    # stdin_open: true  
  nginx:
    image: nginx 
    ports: 
      - "3000:80" 